version: '3.7'
name: ohlc-data-pipeline
services:

  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.19

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.8

    depends_on:
      - redpanda